### ISSUE TITLE
Proto failed symlink in pipeline

### ISSUE THREAD

**Issue by Blissful89** [moonrepo/setup-toolchain#19]
**Describe the bug**

I am using python v3.13.1 in my `.prototools` and am trying to setup a pipeline to run `moon ci :lint`. The proto tooling, together with setup-toolchain, is failing to locate and symlink the python binaries after install. I have tried clearing all toolchain caches but repeated runs fail.

<img width="1792" alt="Image" src="https://github.com/user-attachments/assets/21bc1536-b26c-4dce-95c7-97dc83a49f89" />

After running `proto bin python` in de pipeline in a subsequent run, one can see the binary is installed at `/home/runner/.proto/tools/python/3.13.1/bin/python`, whilst later on the pipeline is trying to symlink `/home/runner/.proto/tools/python/3.13.1/install/bin/python3`

<img width="1724" alt="Image" src="https://github.com/user-attachments/assets/c8b19b7f-35f7-4dce-bb4d-dc799788c9d0" />

**Steps to reproduce**

1. create `.prototools` with content
    ```toml
    python = "~3.13"
    ```
2. run python command from moon using setup-toolchain
    ```yaml
        - name: Inject Moon
          uses: moonrepo/setup-toolchain@v0
          with:
            auto-install: true

        - name: Lint projects
          run: moon ci :lint
          shell: bash
    ```

**Notable**
Maybe the release of [proto v0.45.0](https://github.com/moonrepo/proto/releases/tag/v0.45.0) is part of this issue? I am however incapable of reproducing this issue locally, and it only seems to affect our ci/cd.
