### ISSUE TITLE
[bug] Cannot select moon version other than the latest

### ISSUE THREAD

**Issue by hckhanh** [moonrepo/setup-toolchain#2]
Due to https://github.com/moonrepo/moon/issues/1095, I need to downgrade moon version on CI

I get this issue when choosing a moon version: `Command failed with exit code 22: /home/runner/.proto/temp/moon.sh 1.14.13`

```yml
name: Cypress

jobs:
  test:
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Disabling shallow clone is recommended for improving relevancy of reporting
      - name: Setup moon
        uses: moonrepo/setup-toolchain@v0
        with:
          moon-version: '1.14.13'
```

**Comment by milesj** [comment]
Interesting, looks like exit code 22 is a curl failure??? Let me check the install script.

**Comment by milesj** [comment]
@hckhanh Made some minor changes to the install scripts and this action, let me know if it's still happening.

**Comment by hckhanh** [comment]
It's still happening

```
Error: Error: Command failed with exit code 22: /home/runner/.proto/temp/moon.sh 1.14.13
curl: (22) The requested URL returned error: 404
```

**Comment by milesj** [comment]
@hckhanh We test installing versions in CI, so I'm positive this works: https://github.com/moonrepo/moon/actions/runs/6422531016/job/17439200224

Is this a self hosted runner? I have a feeling something else is going on unrelated to the install scripts. Maybe some kind of caching in the environment?

Installing by latest or by version is basically the same curl request: https://github.com/moonrepo/moon/blob/master/website/static/install/moon.sh#L46

**Comment by hckhanh** [comment]
@milesj this is my workflow. I am using GitHub cloud runner.

```yml
name: Lints

on:
  workflow_call:

concurrency:
  group: lints-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lints:
    name: Lints
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup moon
        uses: moonrepo/setup-toolchain@v0
        with:
          moon-version: '1.14.13'
      - name: Get cache
        uses: actions/cache@v3
        with:
          path: |
            ./.moon/cache
          key: ${{ runner.os }}-lints-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-lints-
      - name: Check lints
        run: moon ci :lints
```
