### ISSUE TITLE
Missing proto version on upload cache key

### ISSUE THREAD

**Issue by arthur-leclerc** [moonrepo/setup-toolchain#21]
# Cache Key Issue with Proto Version

## Problem Description

When the cache key is created, it includes the hash of the Proto version.

Debug logs clearly show that the version is being used in the cache key generation:

```
##[debug]Found 1 files to hash.
##[debug]Hashing proto version: 0.47.5
```

When [looking at the code](https://github.com/moonrepo/setup-toolchain/blob/master/helpers.ts#L118-L124), this version comes from the `PROTO_CLI_VERSION` env variable who's set somewhere, maybe during the installation of the Proto CLI?

When restoring the cache, the `PROTO_CLI_VERSION` is not set, resulting in a different cache key.

Adding `PROTO_CLI_VERSION` to the action make it work as expected.

```yaml
- uses: moonrepo/setup-toolchain@v0
with:
    auto-install: true
    # Only used to make sure to use the same version as the cache key
    proto-version: "0.47.5"
env:
    # Needed by post steps to generate the right cache key with Proto version added to the hash
    PROTO_CLI_VERSION: "0.47.5"
```
